# Generated by Django 3.0.4 on 2020-11-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201118_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identification',
        ),
    ]
