# Generated by Django 3.0.4 on 2020-11-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_name',
        ),
    ]
