# Generated by Django 3.1.4 on 2020-12-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_items/')),
                ('type_image', models.IntegerField(choices=[(1, 'ImageType1'), (2, 'ImageType2'), (3, 'ImageType3')], default=0)),
            ],
            options={
                'db_table': 'item_images',
            },
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='last_name',
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'WaitAccept'), (2, 'Accept'), (3, 'Success')], default=1),
        ),
    ]
