# Generated by Django 3.1.4 on 2020-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(0, 'Init'), (2, 'Payment success'), (2, 'Payment fail'), (3, 'Delivering'), (4, 'Done'), (5, 'Refund')], default=1),
        ),
    ]
