# Generated by Django 3.1.4 on 2020-12-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
