# Generated by Django 3.0.4 on 2020-11-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_items/')),
                ('type_image', models.IntegerField(choices=[(1, 'ImageType1'), (2, 'ImageType2'), (3, 'ImageType3')], default=0)),
            ],
            options={
                'db_table': 'item_images',
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='items',
            name='image3',
        ),
    ]
