# Generated by Django 3.0.4 on 2020-11-25 07:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0002_auto_20201125_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
