# Generated by Django 3.0.4 on 2020-11-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0003_items_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'WaitAccept'), (2, 'Accept'), (3, 'Success')], default=1),
        ),
    ]
