# Generated by Django 3.1.4 on 2021-01-04 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0003_orders_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Credit Card')]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(0, 'Init'), (1, 'Payment success'), (2, 'Payment fail'), (3, 'Delivering'), (4, 'Done'), (5, 'Refund')], default=0),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('unit_price', models.IntegerField(default=None)),
                ('total_price', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_admin.items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_admin.orders')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
