# Generated by Django 3.1.4 on 2020-12-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0004_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
    ]
